### ISSUE TITLE
Themes menu added, but changing themes from default results in no syntax highlighting

### ISSUE THREAD

**Issue by zbeekman** [merqurio/jupyter_themes#10]
No syntax highlighting happens when changing themes. Only default theme has highlighting.

**Comment by merqurio** [comment]
Thanks for the report. Would you mind sharing the error log from the browser console so I can help you debugging it. 

[Chrome](https://developers.google.com/web/tools/chrome-devtools/)
[Firefox](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console)

**Comment by kristomi** [comment]
I have the same problem. The fonts load fine, but not the syntax highlighting. I am using pyenv virtualenvs, and have put the extensions inside the "versions/3.6.2/etc/jupyter/nbextensions" folder.  Here is the output from the console log

![image](https://user-images.githubusercontent.com/6913891/33513729-ff11d272-d748-11e7-98ce-7b85b5ddaf95.png)

**Comment by dabro** [comment]
I'm having the same problem.  As above, the plugin is calling directly to `http://static/components/codemirror/theme/3024-day.css?v=20171218223519`, as opposed to `http://localhost:8888/static/...`.

I tried running `require.toUrl()` in the console, and it seems to be failing to add the hostname.  I assume that's what it's supposed to do? 
```
>>require.toUrl("/static/components/codemirror/theme/3024-day.css")
"/static/components/codemirror/theme/3024-day.css?v=20171218223519"
```
I verified that manually adding localhost to the url and calling it from a separate tab returned the css file correctly.

**Comment by merqurio** [comment]
Thanks @dabro ! I'll check it and ping you all

**Comment by mgsosna** [comment]
Hi, I was wondering if there have been any changes? Syntax highlighting only works on the Default theme. Thanks!

**Comment by merqurio** [comment]
hi @mmgrobis , @dabro and @zbeekman I just released a modification that should solve the problem. Please let me know if it worked.
