### ISSUE TITLE
ink.href = Jupyter.notebook.base_url + require.toUrl(themes[theme]);  NOT WORKING?

### ISSUE THREAD

**Issue by jmbertoncelli** [merqurio/jupyter_themes#11]
I did apply this temporary fix:

    function load_css(theme) {
        // Create a link element to attach the styles
        var link = document.createElement("link");
        link.type = "text/css";
        link.rel = "stylesheet";
        //link.href = Jupyter.notebook.base_url + require.toUrl(themes[theme]);
	link.href = window.location.origin + require.toUrl(themes[theme]);
        link.id = theme + "-css";
        document.getElementsByTagName("head")[0].appendChild(link);
    }

Thanks!

**Comment by merqurio** [comment]
Great ! Do you mind if I do a pull request using this code ? I'll mention you as author of the fix, or if you prefer I'll gladly accept a PR 😁

**Comment by merqurio** [comment]
It makes sense, maybe this would fix #10 too

**Comment by jmbertoncelli** [comment]
Of course!  Thanks for this great extension!

Sent from my iPhone

On Jan 25, 2018, at 4:16 PM, Gabriel de Maeztu <notifications@github.com<mailto:notifications@github.com>> wrote:


It makes sense, maybe this would fix #10<https://github.com/merqurio/jupyter_themes/issues/10> too

**Comment by jrwrigh** [comment]
I can confirm that this fixed the issue in #10 .

**Comment by merqurio** [comment]
Merged ! Thanks @u2berggeist and @jmbertoncelli
