### ISSUE TITLE
works in jupyter but not in jupyter-lab

### ISSUE THREAD

**Issue by Omid888** [merqurio/jupyter_themes#13]
I appreciate your tool which is indeed helpful.
I would like to ask you for support of jupyter lab.
thank you.

**Comment by DanielGoldfarb** [comment]
@merqurio 
Gabi,  
I love this extension.  Recently I moved from jupyter notebook to jupyter-lab and, as noted above by @Omid888, can't seem to get it to work in jupyter-lab.   Any advice?   I will gladly write the code if needed, if you can provide some guidance (not sure where to start).   Thanks.   All the best.   --Daniel
