### ISSUE TITLE
Themes unsupported in Editr

### ISSUE THREAD

**Issue by maver1ck** [merqurio/jupyter_themes#2]
Hi,
Is it possible to add theme support to file editor ?

**Comment by merqurio** [comment]
I'll try to check it, I'm not sure how can I inject CSS to the file editor :grinning:

**Comment by maver1ck** [comment]
Hi,
Did you make it ?
Maybe I can help somehow.

**Comment by merqurio** [comment]
Not yet, I haven't figured out how to add js or CSS to it :grin:
