### ISSUE TITLE
No themes in "Cell" menu

### ISSUE THREAD

**Issue by Eleonore9** [merqurio/jupyter_themes#5]
I must have missed a step somewhere. 
I have the theme plugin in my `nbextensions` directory: 
![jupyter_themes](https://cloud.githubusercontent.com/assets/2502761/14103676/23b237a4-f599-11e5-8654-04f571bdbc61.png)
still I can't see the themes in my "Cell" menu:
![jupyter_cell_menu](https://cloud.githubusercontent.com/assets/2502761/14103678/27ea2b1a-f599-11e5-9b16-0866fd3d46cc.png)

**Comment by merqurio** [comment]
uhm, let's check this so we can find the problem fastly:
- Check Jupyter version with  `jupyter --version`
- Be sure, [last version](https://github.com/merqurio/jupyter_themes/commit/01d7594bbe0d2103d5ad96a2da7119345ff6ade7) of the plugin is installed
- Please [check your console](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-ui?hl=en) for any errors in the JS

Thanks for testing it !

**Comment by Eleonore9** [comment]
Thanks for your help @merqurio!
- 

```
jupyter --version
4.1.0
```
- I manually replaced by the newest version of [theme_selector.js](https://raw.githubusercontent.com/merqurio/jupyter_themes/01d7594bbe0d2103d5ad96a2da7119345ff6ade7/theme_selector.js)
- There's an error in the console. I'm missing a script called `extension.js`. Where can I download it?
  ![error_notebook](https://cloud.githubusercontent.com/assets/2502761/14182651/3367c944-f764-11e5-8a1d-1a01f3a7ec09.png)

**Comment by merqurio** [comment]
Ok, I see by the last line of the photo that `theme_selector.js` was loaded, was there any error after it ?
- What browser do you use ?
- In which OS
- Can you try to clean cache ? (304 code means the browser is using the cached version)

Sorry for this and thanks for helping me making it better !

**Comment by Eleonore9** [comment]
- browser: FF 45.0
- OS: Ubuntu 14.04
- clearing the cache didn't seem to change anything

Is extension.js something to be installed separately?

Thanks for your help!

**Comment by merqurio** [comment]
`extension.js` It's not a file of us :confused: . I'm going to investigate if this is a problem of Jupyter. I wasn't able to reproduce the problem with OSX and FF45.0

I'm sure you did this right, but just to see if it was correctly installed can you do a `pwd`at `cd $(jupyter --data-dir)/nbextensions`?

I know the installation path is diff in Linux, let's make it work there if it isn't.

Also, do you use conda ?

Thanks !

**Comment by Eleonore9** [comment]
I do not use conda.

```
pwd
/home/<username>/.ipython/nbextensions
```

**Comment by merqurio** [comment]
can you try to do a `jupyter nbextension enable nbextensions/jupyter_themes` ? if not try to disable and then enable.

Thanks for your help debugging this, I understand it can be tedious

**Comment by merqurio** [comment]
Also, can you please do a `cat $(jupyter --config-dir)/nbconfig/notebook.json` ? you should get something like this:

``` json
{
  "load_extensions": {
    "jupyter_themes/theme_selector": true
  }
}
```

And this is how it looks if you modify anything using the plugin:

``` json
{
  "load_extensions": {
    "jupyter_themes/theme_selector": true
  },
  "CodeCell": {
    "cm_config": {
      "theme": "material",
      "font_family": "Hack",
      "lineNumbers": true
    }
  }
}
```

**Comment by Eleonore9** [comment]
When I do `jupyter nbextension enable nbextensions/jupyter_themes`, I get a **404** for `jupyter_themes.js`.

**Comment by Eleonore9** [comment]
```
~ » cat .jupyter/nbconfig/notebook.json      
```

```
{
  "load_extensions": {
    "livereveal/main": true, 
    "jupyter_themes/theme_selector": true
  }
}
```

**Comment by merqurio** [comment]
sorry I meant `jupyter nbextension enable jupyter_themes/theme_selector`my bad :disappointed:

**Comment by Eleonore9** [comment]
No problem!
It doesn't help either I'm afraid :confused:
