### ISSUE TITLE
Better not to assume base URL

### ISSUE THREAD

**Issue by dlukes** [merqurio/jupyter_themes#7]
Hi, first of all, thanks for a really useful extension! :) And one small remark: when loading assets, it's better not to assume that the base URL is `/`. In my case for instance, I'm running a JupyterHub server which spawns notebooks for individual users, so the base URLs are `/user/<username>`.

Details in the following commit: https://github.com/dlukes/jupyter_themes/commit/f2e498ba060484d6253ec033622b834895143dda

Let me know if you want me to start a PR :)

**Comment by merqurio** [comment]
Thanks @dlukes  ! sorry for the delay
Please PR are more than welcome !  @PythonSanSebastian is having this issue right now too
